version: "3.8"
services:
   web:
     image: "${IMAGE}"
     ports:
     - "8001:80"
     depends_on:
     - mysql
   mysql:
     image: poojaj2406/mysql:emp
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
     volumes:
     - db_data:/var/lib/mysql
volumes:
   db_data: {}
